export const LOAD_COURSES_SUCESS = "LOAD_COURSES_SUCESS";
export const LOAD_AUTHORS_SUCESS = "LOAD_AUTHORS_SUCESS";
export const UPDATE_COURSE_SUCESS = "UPDATE_COURSE_SUCESS";
export const CREATE_COURSE_SUCESS = "CREATE_COURSE_SUCESS";
